# Generated by Django 4.1.4 on 2022-12-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customusermodel_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='/media/default/img_avatar.png', upload_to='default/'),
        ),
    ]
