# Generated by Django 4.1.4 on 2023-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='media/default_avatar/author.webp', upload_to='profile_avatar/'),
        ),
    ]
