# Generated by Django 4.1.4 on 2024-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customusermodel_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='applied_discounts',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
