# Generated by Django 4.1.4 on 2024-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customusermodel_applied_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='applied_discounts',
        ),
    ]
