# Generated by Django 4.1.4 on 2023-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='media\x08log_images\x01-570x370.webp', null=True, upload_to='blog_images/'),
        ),
    ]
