# Generated by Django 4.1.4 on 2023-09-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='list_view_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='detail_view_image',
            field=models.ImageField(blank=True, default='media\x08log_images\x01-870x500.webp', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='small_detail_view_image',
            field=models.ImageField(blank=True, default='media\x08log_images\x01-420x241.webp', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
    ]
