# Generated by Django 4.1.4 on 2023-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_image_blog_list_view_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='small_detail_view_image_2',
            field=models.ImageField(blank=True, default='media\x08log_images\x01-420x241.webp', null=True, upload_to='blog_images/'),
        ),
    ]
