# Generated by Django 4.1.4 on 2023-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts_tag', to='blog.tag'),
        ),
    ]
