# Generated by Django 4.1.4 on 2023-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
