# Generated by Django 4.2.11 on 2024-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified_data',
            new_name='datetime_modified',
        ),
        migrations.AddField(
            model_name='post',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
