# Generated by Django 4.1.4 on 2023-10-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('p', 'PAID'), ('u', 'UNPAID'), ('c', 'CANCELED')], default='u', max_length=100),
        ),
    ]
