# Generated by Django 4.1.4 on 2023-12-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_address_remove_order_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwithaddress',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
