# Generated by Django 4.1.4 on 2023-12-26 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_alter_customerwithaddress_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwithaddress',
            name='country',
            field=models.CharField(choices=[('TURKEY', 'turkey'), ('IRAN', 'iran'), ('IRAQ', 'iraq'), ('BAHRAIN', 'bahrain'), ('UAE', 'united arabic emirates')], max_length=250),
        ),
        migrations.AlterField(
            model_name='customerwithaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
