# Generated by Django 4.1.4 on 2023-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(max_length=20),
        ),
    ]
