# Generated by Django 4.1.4 on 2023-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID'), ('Canceled', 'CANCELED')], default='u', max_length=100),
        ),
    ]
