# Generated by Django 4.1.4 on 2024-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discounted_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
