# Generated by Django 4.1.4 on 2024-03-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discounted_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
