# Generated by Django 4.2.11 on 2024-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_order_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signal',
            field=models.BooleanField(default=False),
        ),
    ]
