# Generated by Django 4.2.11 on 2024-10-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_signal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='signal',
            new_name='canceled_signal',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_signal',
            field=models.BooleanField(default=False),
        ),
    ]
