# Generated by Django 4.1.4 on 2023-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
