# Generated by Django 4.1.4 on 2023-01-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('NONE CATEGORY', 'none category'), ('HOME AND KITCHEN', 'home and kitchen'), ('SPORT', 'sport'), ('LOCAL PRODUCTS', 'local products'), ('TOYS', 'toys'), ('COMMODITY', 'commodity'), ('FASHION AND CLOTHING', 'fashion and clothing'), ('TOOLS AND EQUIPMENT', 'tools and equipment'), ('DIGITAL COMMODITY', 'digital commodity')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
