# Generated by Django 4.1.4 on 2023-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_comment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
