# Generated by Django 4.1.4 on 2023-01-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
