# Generated by Django 4.1.4 on 2023-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('POOR', '1'), ('BAD', '2'), ('NORMAL', '3'), ('GOOD', '4'), ('PERFECT', '5')], max_length=100, null=True),
        ),
    ]
