# Generated by Django 4.1.4 on 2023-01-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_category_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
