# Generated by Django 4.1.4 on 2023-10-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('POOR', 'poor'), ('BAD', 'bad'), ('NORMAL', 'normal'), ('GOOD', 'good'), ('PERFECT', 'perfect')], max_length=100, null=True),
        ),
    ]
