# Generated by Django 4.1.4 on 2023-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory_name',
        ),
    ]
