# Generated by Django 4.1.4 on 2023-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PD', 'PERCNTAGE DISCOUNT'), ('FAD', 'FIXED AMOUNT DISCOUNT'), ('BOGO', 'BUY ONE GET ONE')], max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('expiration_data', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(related_name='discounts', to='products.discount'),
        ),
    ]
