# Generated by Django 4.1.4 on 2023-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_discount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_status',
            field=models.CharField(choices=[('AC', 'ACTIVE'), ('DC', 'DIACTIVE')], default='ACTIVE', max_length=255),
        ),
    ]
