# Generated by Django 4.1.4 on 2023-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_discount_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_status',
            field=models.CharField(choices=[('AC', 'ACTIVE'), ('DC', 'DIACTIVE')], default='AC', max_length=255),
        ),
    ]
