# Generated by Django 4.1.4 on 2023-10-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_discount_discount_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_type',
            new_name='type',
        ),
    ]
