# Generated by Django 4.1.4 on 2023-02-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_color_product_is_featured_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
