# Generated by Django 4.1.4 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_discount_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounts',
            field=models.ManyToManyField(related_name='products', to='products.discount'),
        ),
    ]
