# Generated by Django 4.1.4 on 2023-11-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_discounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_status',
            new_name='status',
        ),
    ]
