# Generated by Django 4.1.4 on 2023-11-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
    ]
