# Generated by Django 4.1.4 on 2023-02-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_comments_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rating',
        ),
    ]
