# Generated by Django 4.1.4 on 2023-11-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='selected_product',
        ),
    ]
