# Generated by Django 4.1.4 on 2023-11-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_category_selected_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('PD', 'PERCENTAGE DISCOUNT'), ('FAD', 'FIXED AMOUNT DISCOUNT')], max_length=255),
        ),
    ]
