# Generated by Django 4.1.4 on 2023-02-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
