# Generated by Django 4.1.4 on 2023-02-18 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0032_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_wished_product',
            field=models.ManyToManyField(blank=True, related_name='wished_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
