# Generated by Django 4.1.4 on 2023-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_color_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('LARGE', 'large'), ('MEDIUM', 'medium'), ('SMALL', 'small')], default=('BLACK', 'black'), max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('BLACK', 'black'), ('WHITE', 'white'), ('PINK', 'pink')], default=('LARGE', 'large'), max_length=200),
        ),
    ]
