# Generated by Django 4.1.4 on 2023-02-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_product_user_wished_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
