# Generated by Django 4.1.4 on 2023-12-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
