# Generated by Django 4.1.4 on 2023-02-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_color_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
