# Generated by Django 4.1.4 on 2023-12-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_product_is_active_remove_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rekjljlg',
            field=models.BooleanField(default=True),
        ),
    ]
