# Generated by Django 4.1.4 on 2023-12-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_product_is_rekjljlg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_rekjljlg',
            new_name='activation',
        ),
    ]
