# Generated by Django 4.1.4 on 2023-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_rename_is_rekjljlg_product_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
