# Generated by Django 4.1.4 on 2023-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_comment_email_comment_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='session_token_number',
        ),
        migrations.AddField(
            model_name='comment',
            name='session_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
