# Generated by Django 4.1.4 on 2023-12-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='product_banners/'),
        ),
    ]
