# Generated by Django 4.1.4 on 2024-01-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
