# Generated by Django 4.1.4 on 2024-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_category_selected_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='promo_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
