# Generated by Django 4.1.4 on 2024-02-08 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_discount_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='datetime_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='datetime_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 20, 22, 24, 375903)),
        ),
    ]
