# Generated by Django 4.1.4 on 2024-02-08 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_discount_datetime_created_discount_datetime_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 7, 53, 508008)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='promo_code',
            field=models.CharField(max_length=4),
        ),
    ]
