# Generated by Django 4.1.4 on 2024-02-08 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_discount_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 48, 28, 762745)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='promo_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
