# Generated by Django 4.1.4 on 2024-02-17 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_discount_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 15, 10, 50, 24024, tzinfo=datetime.timezone.utc)),
        ),
    ]
