# Generated by Django 4.1.4 on 2024-02-18 10:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_discount_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 10, 27, 8, 216919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10000000), django.core.validators.MinValueValidator(limit_value=1000)]),
        ),
    ]
