# Generated by Django 4.1.4 on 2024-02-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_alter_discount_expiration_date_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 10, 27, 28, 754462, tzinfo=datetime.timezone.utc)),
        ),
    ]
