# Generated by Django 4.1.4 on 2024-02-27 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_product_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
