# Generated by Django 4.1.4 on 2024-03-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_alter_discount_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
