# Generated by Django 4.1.4 on 2024-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_alter_discount_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='session_restore',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
