# Generated by Django 4.1.4 on 2024-03-10 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0067_discount_session_restore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='session_restore',
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
