# Generated by Django 4.2.11 on 2024-04-02 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_alter_discount_usage_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
