# Generated by Django 4.2.11 on 2024-10-15 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_alter_discount_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 25, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
