# Generated by Django 4.2.11 on 2024-10-20 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_alter_discount_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
