# Generated by Django 4.2.11 on 2024-10-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
