# Generated by Django 4.2.11 on 2024-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
